# Generated by Django 3.2.3 on 2026-05-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0002_alter_cat_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('ongoing', 'В пути'), ('completed', 'Завершено')], default='planned', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='cats.cat')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='travels.destination')),
            ],
        ),
    ]
